baseURL = "https://covesa.github.io/vehicle_signal_specification/"
languageCode = "en-us"
title = "Vehicle Signal Specification"
theme = "learn"
publishDir = "../docs"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  disableInlineCopyToClipBoard = true
  editURL = "https://github.com/covesa/vehicle_signal_specification/edit/master/docs-gen/content/"
  disableLandingPageButton = true


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/covesa/vehicle_signal_specification"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-download'></i> Releases"
url = "https://github.com/covesa/vehicle_signal_specification/releases"
weight = 12

# Generation of JSON index to allow search
[outputs]
home = [ "HTML", "RSS", "JSON"]
